### PR TITLE
Fix zero prio tasks when all async tasks have default (no) arguments

### PR DESCRIPTION
**Pull request by korken89**
Without this fix the default tasks get priority 1 instead of the intended 0.

### CODE REVIEW

**Review by AfoHT — DISMISSED** [review]
Bors merge

**Comment by datdenkikniet** [comment]
bors try

**Comment by korken89** [comment]
bors try

**Review by datdenkikniet — APPROVED** [review]

**Comment by korken89** [comment]
bors r=datdenkikneit

**Comment by korken89** [comment]
bors retry

**Comment by korken89** [comment]
bors retry

**Pull request merged**
