### PR TITLE
Bump rp2040-pac to 0.6 in rtic-monotonics

### PR DESCRIPTION
**Pull request by martinsp**
⚠️ `examples/rp2040_local_i2c_init` depends on unreleased https://github.com/rp-rs/rp-hal-boards/pull/60

### CODE REVIEW

**Comment by korken89** [comment]
Thanks for the PR! Can you have a look at fixing the failing test?

**Comment by martinsp** [comment]
Looks like this needs to wait for https://github.com/rp-rs/rp-hal-boards/pull/60 otherwise there are two versions of `rp204-pac` pulled in in the `examples/rp2040_local_i2c_init` and causes conflicting types.
- rp2040-pac 0.5 through rp-pico -> rp2040-hal (0.9.2)
- rp2040-pac 0.6 through rtic-monotonic

**Comment by korken89** [comment]
I gave this a look now, I think this is a breaking change no? As this would make the RP2040 monotonic stop working with the older PACs.
We've not set a policy yet on how we see breaking PAC changes, but lets add this to tomorrows meeting.
I'm fine with tracking the latest PACs as the contract of `rtic-monotonics` but lets see what others think.

Else one needs to add a feature flag for specific PAC version spans as breaking changes come.

**Review by korken89 — APPROVED** [review]
Since we will do a major release this is now fine!

**Pull request merged**
