### PR TITLE
Fix STM32 Monotonic for peripherals with only two Clock Compare modules

### LINKED ISSUE #956: rtic-monotonic panics
I managed to get monotonic panic. TIM3 on stm32g030k6 should be 16bit timer.

```toml
embassy-stm32 = { git = "https://github.com/embassy-rs/embassy.git", rev = "000b022ae2e52e9abaabbd10110b4c583fe4344c", features = [
    "defmt",
    "stm32g030k6",
    "unstable-pac",
    "exti",
] }
rtic-monotonics = { version = "2.0.1", features = [
    "stm32g030k6",
    "stm32_tim3",
] }
rtic-sync = "1.3"
rtic = { version = "2.1", features = ["thumbv6-backend"] }

```

```
15439 INFO  periodic
└─ ptubasehub::app::input_events::{async_fn#0} @ src/main.rs:176
33074 INFO  periodic
└─ ptubasehub::app::input_events::{async_fn#0} @ src/main.rs:176
32779 ERROR panicked at /Users/andres/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rtic-monotonics-2.0.1/src/stm32.rs:338:1:
Monotonic must have missed an interrupt!
└─ panic_probe::print_defmt::print @ /Users/andres/.cargo/registry/src/index.crates.io-6f17d22bba15001f/panic-probe-0.3.1/src/lib.rs:104
```

### PR DESCRIPTION
**Pull request by Finomnis**
Fixes #956.
Replaces #958.

Rationale: Some timer peripherals seem to have only two clock compare modules. Therefore the half period interrupt does not fire and the monotonic sanity check triggers.

Solution: Use CC1 instead of CC3. This was more or less a typo anyway; we originally intended to use CC1 and CC2, we just ended up using CC2 and CC3 because we didn't realize that the enumeration starts with 0.

Review: @korken89

### CODE REVIEW

**Comment by Finomnis** [comment]
Seems to still run fine on my stm32g030, indicating that the CC indices indeed start at 0.

@great-houk, would you mind testing if this fixes your problem?

EDIT: Ran for 3800 seconds now, still fine.

**Comment by great-houk** [comment]
I can confirm it works, thanks for your help.

**Review by korken89 — APPROVED** [review]
Thanks for the fix!

**Comment by Finomnis** [comment]
> Thanks for the fix!

@korken89 Might want to yank the previous two releases if such a serious bug existed.

**Pull request merged**
